### ISSUE TITLE
Could not open database file: Hangfire.db (CannotOpen)

### ISSUE THREAD

**Issue by Pinhead877** [raisedapp/Hangfire.Storage.SQLite#21]
Hi there 

is there any permissions needed in order to create the sqlilte db instance?

`
                GlobalConfiguration.Configuration.UseSQLiteStorage();
`
Thanks
Alex

**Comment by felixclase** [comment]
Hi,

Do you have any additional process that is using the database file?

Try deleting it and running the project again as an administrator (if you are on Windows)

**Comment by Pinhead877** [comment]
From the looks of it, the db file wasn't created at all. so there is nothing to delete.

**Comment by Pinhead877** [comment]
For future references this is what worked for me:

`
                Directory.CreateDirectory(@"c:\hangFire");
                GlobalConfiguration.Configuration.UseSQLiteStorage(@"c:\hangFire\hangFire.db");
`

The directory that was created by the app had permissions to create the db file. after that everything worked.
