### ISSUE TITLE
SQLiteMonitoringApi dictionary errors

### ISSUE THREAD

**Issue by CesarStatik** [raisedapp/Hangfire.Storage.SQLite#25]
Hi Felix,

I noticed that the issue still exist for the functions "ScheduledJobs", "ProcessingJobs" and "FailedJobs" on the "SQLiteMonitoringApi"class, It seems that you missed adding validations on "ExceptionDetails", "ExceptionMessage" and "ExceptionType" in the "FailedJobs" function, "StartedAt" in the "ProcessingJobs" function and "ScheduledAt" in the "ScheduledJobs" function.

Can you please include this validations?

**Comment by felixclase** [comment]
Hi,

I have tried to replicate the inconvenience you have several times and it has not happened to me.

Could you share the code you are using?
