### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by Bunabun** [raisedapp/Hangfire.Storage.SQLite#26]
Would anyone or the author consider this project to be ready for production environments yet, or are there significant limitations that haven't been worked out?

**Comment by Bunabun** [comment]
I should have read the readme more closely, sorry.

**Comment by felixclase** [comment]
I currently use it for some processes that I have in my current job, of course in production.

So far I have not had any inconvenience.

![image](https://user-images.githubusercontent.com/1153361/75889330-21035200-5e03-11ea-9681-9a3d714486d9.png)

![image](https://user-images.githubusercontent.com/1153361/75889361-2e204100-5e03-11ea-922f-28cd91f26cf3.png)
