### ISSUE TITLE
UseSQLiteStorage: wrong argument name - nameOrConnectionString

### ISSUE THREAD

**Issue by petarpetrovt** [raisedapp/Hangfire.Storage.SQLite#27]
Extension method `UseSQLiteStorage` has a argument named `nameOrConnectionString` but the `sqlite-net` library's `SQLiteConnection` takes `databasePath` as argument.

## Doesn't work
 * UseSQLiteStorage($"Data Source={pathToDbFile};Version=3;")
 * UseSQLiteStorage("Hangfire")

## Works
* UseSQLiteStorage(pathToDbFile)

**Comment by felixclase** [comment]
The change has already been implemented, I will be publishing the new version.

**Comment by aradalvand** [comment]
@felixclase Sorry, I'm still seeing the old argument name?! It doesn't seem to have changed:
https://github.com/raisedapp/Hangfire.Storage.SQLite/blob/65c37b8bf1d8a901312b273342a57000b5c600c7/src/main/Hangfire.Storage.SQLite/SQLiteStorageExtensions.cs#L37-L40

**Comment by bobinush** [comment]
Since EntityFramework uses connection string instead of path. Here is a tip for future users if you want to have Hangfire in the same db.

```C#
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection"); // "DataSource=app.db"

var sqliteDatabasePath = new SqliteConnectionStringBuilder(connectionString).DataSource; // "app.db"

services.AddHangfire(configuration => configuration
            .UseSimpleAssemblyNameTypeSerializer()
            .UseRecommendedSerializerSettings()
            .UseSQLiteStorage(sqliteDatabasePath));
```
