### ISSUE TITLE
Compatibility with Hangfire.SQLite?

### ISSUE THREAD

**Issue by 0xced** [raisedapp/Hangfire.Storage.SQLite#4]
Are you planning to make your project compatible with [Hangfire.SQLite](https://www.nuget.org/packages/Hangfire.SQLite/)? I.e. will the db structure be compatible? In either case, please consider being explicit about the compatibility in the README.

**Comment by felixclase** [comment]
Hi,

For the first version of this storage I do not think it is possible, first I want to finish the project and that it works correctly, then I could see if the structure of the Hangfire.SQLite database will be compatible with it.

**Comment by felixclase** [comment]
dismissed
