### ISSUE TITLE
How Can we configure Auto Clean up for sqlitedb after specific time 

### ISSUE THREAD

**Issue by MohamedRagab10793-design** [raisedapp/Hangfire.Storage.SQLite#45]

**Comment by felixclase** [comment]
Hello @MohamedRagab10793-design ,

Use the **AutoVacuumSelected** option when configuring the storage,

`
            services.AddHangfire(configuration => configuration
                .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                .UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UseSQLiteStorage("Hangfire.db", new SQLiteStorageOptions() { AutoVacuumSelected = SQLiteStorageOptions.AutoVacuum.FULL });
`

https://www.techonthenet.com/sqlite/auto_vacuum.php
