### ISSUE TITLE
There is any configuration way to decrease HangFire sqlitedb file after specific size or specific time ?

### ISSUE THREAD

**Issue by MohamedRagab10793-design** [raisedapp/Hangfire.Storage.SQLite#49]
HangFire sqlitedb file get bigger every day 
I want any configuration way to delete records from all tables that created from one week ago

**Comment by felixclase** [comment]
Hello,

Could you tell me if you are using any additional plugin and how big is the sqlite file?

With the auto vacumm configuration I wrote for you, the file size will be kept small because every hour the ExpirationManager is run to delete the oldest records from the database.

**Comment by felixclase** [comment]
https://stackoverflow.com/questions/34450884/keep-history-of-jobs-executed-for-more-than-1-day-in-hangfire

https://discuss.hangfire.io/t/how-to-configure-the-retention-time-of-job/34

You could try this option to reduce the call history of the jobs configured in Hangire, by default they expire every 24 hours.

![image](https://user-images.githubusercontent.com/1153361/170512459-852c3a41-a211-4bb7-b05e-7381d2cc8be8.png)

![image](https://user-images.githubusercontent.com/1153361/170512519-b4df467a-d02a-4986-bc65-8e933f2cca34.png)

https://tickstodatetime.azurewebsites.net

**Comment by felixclase** [comment]
Try the autovacumm option

**Comment by MohamedRagab10793-design** [comment]
As I understand that ExpirationManager is run to delete the oldest records from the database for more than 1 day 
Is this done for all jobs Regardless there state?
and if my column "ExpireAt" at "Job" table  always have null value  ExpirationManager  will work or not ? 
and how can i insert value at "ExpireAt" with every job ?

**Comment by MohamedRagab10793-design** [comment]
> Hello,
> 
> Could you tell me if you are using any additional plugin and how big is the sqlite file?
> 
> With the auto vacumm configuration I wrote for you, the file size will be kept small because every hour the ExpirationManager is run to delete the oldest records from the database.

Hello,
 I am use  Hangfire.Core Version=1.7.8.0,  Hangfire.SQLite  Version=1.4.2.0
As I understand that ExpirationManager is run to delete the oldest records from the database
1- I can't found "AutoVacuumSelected" at SQLiteStorageOptions  class (is this because of my packages versions ?)

![Untitled](https://user-images.githubusercontent.com/64009979/170606634-77c7fe34-398a-4972-8fe0-909c72b753e1.png)



2- Is ExpirationManager work  for all jobs Regardless there state?
3- if my column "ExpireAt" at "Job" table always have null value ExpirationManager will work or not ?
 and how can I insert value at "ExpireAt" with every job ?
![Untitled1](https://user-images.githubusercontent.com/64009979/170607173-5499eec3-f388-4d86-a137-87dba50a65f0.png)

**Comment by felixclase** [comment]
Hello @MohamedRagab10793-design ,

My package is **Hangfire.Storage.SQLite** (https://www.nuget.org/packages/Hangfire.Storage.SQLite), no **Hangfire.SQLite** (https://www.nuget.org/packages/Hangfire.SQLite/).

Try the correct package, the other package was abandoned and that is why I created this one.

**Comment by 0xced** [comment]
For your information: all the issues and pull requests on https://github.com/wanlitao/HangfireExtension (home of Hangfire.SQLite) were closed without any comment a few minutes ago. 🤷‍♀️ I wouldn't be surprised if the repository is archived in the next few minutes.

**Comment by MohamedRagab10793-design** [comment]
> abandoned



> Hello @MohamedRagab10793-design ,
> 
> My package is **Hangfire.Storage.SQLite** (https://www.nuget.org/packages/Hangfire.Storage.SQLite), no **Hangfire.SQLite** (https://www.nuget.org/packages/Hangfire.SQLite/).
> 
> Try the correct package, the other package was abandoned and that is why I created this one.

thank you , i will try your package

**Comment by MohamedRagab10793-design** [comment]
> For your information: all the issues and pull requests on https://github.com/wanlitao/HangfireExtension (home of Hangfire.SQLite) were closed without any comment a few minutes ago. 🤷‍♀️ I wouldn't be surprised if the repository is archived in the next few minutes.

you are right , that what i found
