### ISSUE TITLE
Recommended serializer settings are overwritten by this plugin, causing DateTime timezone problems

### ISSUE THREAD

**Issue by mlaily** [raisedapp/Hangfire.Storage.SQLite#52]
Hello,

Global settings are set by this plugin here https://github.com/raisedapp/Hangfire.Storage.SQLite/blob/32b31a525678efd0431845d3195217c02bda6fcc/src/main/Hangfire.Storage.SQLite/HangfireDbContext.cs#L43-L49

There are two problems:
 1. Overwriting default or user-provided settings inside a plugin is not very nice, and surprising to say the least.
     Since both `.UseSQLiteStorage()` and `.UseRecommendedSerializerSettings()` set this global option, the end value of the serializer settings will be different depending on the order the two methods are called.
 2. The settings used by this plugin are wrong: the `DateFormatString` doesn't contain the timezone format (supposed to be `K` at the end. See https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_DateFormatString.htm)
    This causes issues when using UTC `DateTime` and `DateTimeOffset`.

In my case, I'm using a job with a `DateTimeOffset` argument.  
I enqueue it with an offset of 0 (UTC).  
When the job is called by Hangfire, the  hours and minutes values didn't change, but the offset has been set to my local offset (+1)!

I spent a few hours on this to finally find that `.UseRecommendedSerializerSettings()` after `.UseSQLiteStorage()` instead of before fixes my issue.

**Comment by TomaszCzyz** [comment]
I had a similar issue with `JsonSerializerSettings.TypeNameHandling`. The NuGet package overwrote the recommended value with `TypeNameHandling.None`, which caused incorrect serialization of abstract job arguments. It was a really time-consuming issue to resolve. It would be nice to emphasize that the order of configuration methods matters.

**Comment by dalibor-sanzeru** [comment]
We got issue with de-serializing child object of parent (inheritance) when hangfire de-enqued event.
We solve this by putting
`.UseRecommendedSerializerSettings()`
to the end of AddHangfire chain methods... This is related issue as 
`.UseSQLiteStorage`
really changes serializer settings and has impact to child-parent inheritance deserialization.

**Comment by felixclase** [comment]
Fixed it with version 0.4.0 of the library.
