### ISSUE TITLE
Jobs being assigned wrong IDs on creation

### ISSUE THREAD

**Issue by LiamHowarth** [raisedapp/Hangfire.Storage.SQLite#59]
If a job is created while another thread is inserting a row elsewhere into the DB, it is sometimes assigned the wrong ID due to [this issue](https://github.com/praeclarum/sqlite-net/issues/1168) in the underlying SQLite library.

Because of this, jobs aren't properly initialised, so they are left with a `StateName` of `NULL`, which means they silently fail, and their `JobParameter`s end up being linked to the wrong jobs. If there are lots of jobs being created and run, this ends up happening quite often.

An example of the incorrect IDs being assigned in `SQLiteConnectionFacts`:
```C#
[Fact, CleanDatabase]
public void CreateExpiredJob_CorrectlyPopulatesId_WhenManyThreadsAreInserting()
{
    const int InsertCount = 2000;
    var job = Job.FromExpression(() => SampleMethod("Hello"));
    var parameters = new Dictionary<string, string>();
    var createdAt = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc);
    var expireIn = TimeSpan.FromDays(1);
    
    UseConnection((database, connection) =>
    {
        var lastJobId = int.Parse(connection.CreateExpiredJob(job, parameters, createdAt, expireIn));
        
        var finished = false;
        var ok = true;
        var expectedId = 0;
        string jobId = null;
        
        Parallel.Invoke(
            // Create jobs and break if they are unexpected
            () =>
            {
                for (var insertIndex = 1; insertIndex <= InsertCount; insertIndex++)
                {
                    expectedId = lastJobId + insertIndex;

                    // Inserts the job with the expected ID, but returns the incorrect ID
                    jobId = connection.CreateExpiredJob(job, parameters, createdAt, expireIn);

                    ok = expectedId.ToString() == jobId;
                    if (!ok)
                    {
                        break;
                    }
                }

                finished = true;
            },
            // Another thread inserting rows to the db, e.g. other jobs completing
            () =>
            {
                while (ok && !finished)
                {
                    // Arbitrary database insert
                    database.Database.Insert(new Set());
                }
            }
        );

        if (!ok)
        {
            Assert.Equal(expectedId.ToString(), jobId);
        }
    });
}

```

Note that commenting out the inserting in the second thread fixes the issue

**Comment by kirides** [comment]
Usually things like this are due to misuse of the library at hand, i.e. a single instance that is used as a singleton without synchronization.

It's the same as with EntityFramework not allowing multiple concurrent SQL Commands at the same time in a single DbContext instance.

To fix this, i imagine, we would need to move from a singleton `SQLiteConnection` to per Request/Operation scoped instance.

To do this, we will have to re-design a part of the `SQLiteStorage` to "grab a fresh/pooled instance" as needed and properly clean up/dispose/re-pool afterwards.

**Comment by fnajera-rac-de** [comment]
I had reports from my customers that some jobs were not being executed, while the log files showed no reason for that.

After adding the job id to the log files, it became clear that something was off.

```
...queued -> job Id 99481
...queued -> job Id 99482
...queued -> job Id 301201
...queued -> job Id 99484
```

I saw some work done in devel which might address this - is there any update to this issue?

**Comment by kirides** [comment]
It's very likely that merging develop would fix the cause of this happening.

Previously this library assumed that sqlite (in this case the used sqlite library) was safe to use concurrently from a single connection, which is not the case.

And that usage was corrected and enhanced with some changes on develop
